### ISSUE TITLE
Tutorial Exercise L1.1: Why do we have to make this calculation?

### ISSUE THREAD

**Issue by meier-johannes94** [APMLA-2021/APMLA-WS_21-22_material#3]
Why do we have to make the following calculation? 
![grafik](https://user-images.githubusercontent.com/81717093/139709028-9516695d-55a1-4658-ade0-d65e03416de2.png)

**Comment by mcontisc** [comment]
Hello Johannes. 
Honestly, I think you are referring to the solution of last year and not the current one. 

However, I believe the calculation was posted just to give an alternative to those who struggle to compute derivatives of matrices.

**Comment by meier-johannes94** [comment]
Yes, exactly. Because I can't attend the tutorials each week. Thank you!
