### ISSUE TITLE
Exam Information

### ISSUE THREAD

**Issue by meier-johannes94** [APMLA-2021/APMLA-WS_21-22_material#4]
Two questions :-) : 
- Do we already know the exam date? 
- In the first lecture you said that probably it would be possible for you to upload one of the most recent exams. Is that possible? It would be great!

**Comment by cdebacco** [comment]
Tentative exam dates are: 
    Thursday, 10.02.22
    Monday, 11.04.22 (Nachklausur)
    We are waiting for confirmation of room availability. I just updated the repo with this information. Will notify once Uni admin replies with confirmation. 
    
    Yes, I will upload the .pdf of the most recent exam in the repository.

**Comment by meier-johannes94** [comment]
Thanks a lot!
