### ISSUE TITLE
Question about Lecture 7: 1.1.1 Belief Propagation toy example

### ISSUE THREAD

**Issue by JohanvandenHeuvel** [APMLA-2021/APMLA-WS_21-22_material#6]
I tried working through the example from the lecture notes but it left me very confused:
![image](https://user-images.githubusercontent.com/24225735/145037768-07571747-0efc-4620-b9a7-7ac4c4bfb365.png)

The messages are from variable to variable, so we are using the collapsed equation right:
![image](https://user-images.githubusercontent.com/24225735/145038006-23e3d99d-b599-4bdb-8571-9255a3e18571.png)

- In (6) where does b come from? I can't find a definition that fits this equation.
- In (7) we have messages from 3->2 and 4->2 which suggests we have k=3, and k=4 respectively which would imply we should also sum over x_3 and x_4.
- In (7) we also have a function psi with indexes 1,2 but this only happens with a message from 1->2. It also can't be that the indexes are in the wrong order as k=1 is not possible.
- In (7) Where does the phi_2 come from? Is this psi_22 or the message from 2 to 2? Related, k can take the value 2 right? 
- In (8, 9) Where does the sum over x_3, and x_4 respectively come from? Same for the function psi. I can't match the collapsed equation to those either, even though they are message from variable to variable.

**Comment by cdebacco** [comment]
In (6) where does b come from? I can't find a definition that fits this equation.
**ANSWER**: sorry for the confusion. (6) b1 comes from the definition of marginal, which is in (11), i.e. it comes right after the example. The marginal is calculated exactly like a message update, but including all of the neighbors (not all except one). I thought about this possible confusion, but I needed to first introduce the theorem to be able to justify that definition. I hoped that the example was simple enough to get the intuition of what a marginal on a leaf node could be. I hope this clarifies. 

In (7) we have messages from 3->2 and 4->2 which suggests we have k=3, and k=4 respectively which would imply we should also sum over x_3 and x_4.
**ANSWER**: sorry for the confusion. For that example I did not use the collapsed equations (5), but rather the 2 types of messages (3) and (4) where I collapsed (3) into (4). This leads to a collapsed equation in terms of the function node types of message (i.e. that in (4)) with the hat symbol on top, instead (5) is collapsing everything in terms of the variable node message. The two expressions lead to the same results, it is arbitrary which type of message you want to keep (i.e. the variable node as in (5) or the function node as in the example).
