### ISSUE TITLE
Exercise solutions

### ISSUE THREAD

**Issue by JohanvandenHeuvel** [APMLA-2021/APMLA-WS_21-22_material#7]
Given that the date of the first exam draws closer, could the exercise solutions for at least some of the older exercises be uploaded? That could be very helpful for exam preparation.

**Comment by cdebacco** [comment]
Thanks for letting me know, I just uploaded all the solutions of the tutorials up to Lecture 7. I will upload also the remaining L8-L9 sometime this week

**Comment by JohanvandenHeuvel** [comment]
Thank you!
